# Generated by Django 5.2.6 on 2025-11-09 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
