# Generated by Django 5.2.6 on 2025-11-09 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('goods', '0003_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
